name: PINGO
highlighter: rouge
include: [".htaccess"]
exclude: ["assets/scss", "node_modules", "bower_components", "package.json", "package-lock.json", "gulpfile.js", "README.md", "CNAME", "Gemfile", "Gemfile.lock"]
plugins:
  - jekyll-coffeescript
